version: "3"

services:

  test-vim:
    hostname: test-vim
    privileged: true
    depends_on:
      - test-gdbserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-vim
    working_dir: /root/.vim/plugin/vgdb
    volumes:
      - ..:/root/.vim/plugin/vgdb
      - ../tests/docker_volume_files/vader.vim:/root/.vim/plugin/vader.vim
      - ../tests/docker_volume_files/.vimrc_test:/root/.vimrc
      - ../tests/docker_volume_files/gdb_vars_remote_address.yaml:/root/.vim/plugin/vgdb/plugins/config/gdb_vars_remote_address.yaml
      - ../tests/docker_volume_files/gdb_debug_log_settings.yaml:/root/.vim/plugin/vgdb/plugins/config/gdb_debug_log_settings.yaml
  test-gdbserver:
    hostname: test-gdbserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-server
    working_dir: /work
    security_opt:
      - seccomp:unconfined
    expose:
      - "9999"
    ports:
      - "9999:9999"
    environment:
      - BINARY_TO_RUN
    volumes:
      - ..:/work
      - ${BINARY_LOCATION}:/binaries
    command: /work/scripts/start-server
