version: "3"

services:

  test-vim:
    hostname: test-vim
    privileged: true
    depends_on:
      - test-gdbserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-vim
    working_dir: /root/.vim/plugin/vgdb
    environment:
      - "IN_DOCKER=YES"
      - "DISPLAY=${HOST_IP}:0"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - ..:/root/.vim/plugin/vgdb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
  test-gdbserver:
    hostname: test-gdbserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-server
    working_dir: /work
    security_opt:
      - seccomp:unconfined
    expose:
      - "9999"
    ports:
      - "9999:9999"
    environment:
      - BINARY_TO_RUN
    volumes:
      - ..:/work
      - ${BINARY_LOCATION}:/binaries
    command: /work/scripts/start-server
